const defaults = { text: 'Type Something', fontId: 'Graffiti' };
let state = { ...defaults }; let fonts = []; let requestId = 0; let overview = false;
const $ = (id) => document.getElementById(id);
const el = { text: $('text'), font: $('font'), search: $('font-search'), filter: $('font-filter'), preview: $('preview'), gallery: $('gallery'), stage: $('stage'), notice: $('notice'), status: $('status'), testAll: $('test-all') };

function matchesFilter(font) { const patterns = { none: /.*/, '3d': /3d/i, shadow: /shadow/i, block: /block|banner|standard|big/i, script: /script|graffiti|cursive|hand|calligraphy/i, small: /small|mini|tiny/i }; return patterns[el.filter.value].test(font); }
function fillFonts(query = '') { const results = fonts.filter((font) => matchesFilter(font) && font.toLowerCase().includes(query.toLowerCase())); el.font.replaceChildren(...results.map((font) => new Option(font, font))); if (results.includes(state.fontId)) el.font.value = state.fontId; else if (results.length) { state.fontId = results[0]; el.font.value = state.fontId; } }
function showSingle() { overview = false; el.gallery.hidden = true; el.gallery.replaceChildren(); el.preview.hidden = false; }
function sizeStage(art) { const lines = art.split('\n'); const longest = Math.max(1, ...lines.map((line) => line.length)); el.stage.style.width = `${Math.ceil(longest * 8.43 + 24)}px`; el.stage.style.height = `${Math.ceil(Math.max(1, lines.length) * 17 + 24)}px`; }
function setStatus(message) { el.status.textContent = message; setTimeout(() => { if (el.status.textContent === message) el.status.textContent = ''; }, 2200); }
async function copyArt(art) { try { await navigator.clipboard.writeText(art); setStatus('Raw ASCII copied'); } catch { setStatus('Copy failed; select text manually'); } }
function downloadText(art, filename = 'ascii-art.txt') { const blob = new Blob([art], { type: 'text/plain;charset=utf-8' }); const link = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: filename }); link.click(); URL.revokeObjectURL(link.href); }
function downloadPng(art, filename = 'ascii-art.png') { const lines = art.split('\n'); const width = Math.ceil(Math.max(...lines.map((line) => line.length)) * 8.43 + 48); const height = Math.ceil(lines.length * 17 + 48); const canvas = Object.assign(document.createElement('canvas'), { width, height }); const ctx = canvas.getContext('2d'); ctx.fillStyle = '#101827'; ctx.fillRect(0, 0, width, height); ctx.fillStyle = '#d9f99d'; ctx.font = '14px ui-monospace, SFMono-Regular, Consolas, monospace'; ctx.textBaseline = 'top'; lines.forEach((line, row) => [...line].forEach((char, column) => ctx.fillText(char, 24 + column * 8.43, 24 + row * 17))); const link = Object.assign(document.createElement('a'), { href: canvas.toDataURL('image/png'), download: filename }); link.click(); }
function safeFilename(font) { return `ascii-art-${font.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`; }
async function render() { showSingle(); const id = ++requestId; el.status.textContent = 'Rendering...'; try { const response = await fetch('/api/render', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: state.text, font: state.fontId }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Render failed'); if (id !== requestId) return; el.preview.textContent = payload.art || 'Start typing to create ASCII art.'; sizeStage(payload.art); el.status.textContent = ''; } catch (error) { if (id === requestId) { el.status.textContent = 'Render failed'; el.notice.textContent = error.message; } } }
function fontCard(font, art) { const card = document.createElement('article'); card.className = 'font-card'; const title = document.createElement('h3'); title.textContent = font; const pre = document.createElement('pre'); pre.textContent = art; const actions = document.createElement('div'); actions.className = 'font-card-actions'; const copy = document.createElement('button'); copy.textContent = 'Copy'; copy.addEventListener('click', () => copyArt(art)); const exportPng = document.createElement('button'); exportPng.textContent = 'Export PNG'; exportPng.className = 'secondary'; exportPng.addEventListener('click', () => downloadPng(art, `${safeFilename(font)}.png`)); const exportTxt = document.createElement('button'); exportTxt.textContent = 'TXT'; exportTxt.className = 'secondary'; exportTxt.addEventListener('click', () => downloadText(art, `${safeFilename(font)}.txt`)); actions.append(copy, exportTxt, exportPng); card.append(title, pre, actions); return card; }
async function showAllFonts() { const id = ++requestId; overview = true; el.testAll.disabled = true; el.status.textContent = `Rendering ${fonts.length} fonts...`; try { const response = await fetch('/api/render-all', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: state.text }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Preview failed'); if (id !== requestId || !overview) return; el.preview.hidden = true; el.gallery.replaceChildren(...payload.results.map(({ font, art }) => fontCard(font, art))); el.gallery.hidden = false; el.stage.style.width = '100%'; el.stage.style.height = 'auto'; el.status.textContent = `${payload.results.length} font styles`; } catch (error) { overview = false; el.notice.textContent = error.message; el.status.textContent = 'Preview failed'; } finally { el.testAll.disabled = false; } }

el.text.value = state.text;
el.text.addEventListener('input', (event) => { state.text = event.target.value; render(); }); el.font.addEventListener('change', (event) => { state.fontId = event.target.value; render(); }); el.search.addEventListener('input', (event) => { fillFonts(event.target.value); render(); }); el.filter.addEventListener('change', () => { fillFonts(el.search.value); render(); });
$('copy').addEventListener('click', () => copyArt(el.preview.textContent)); $('download-txt').addEventListener('click', () => downloadText(el.preview.textContent)); $('download-png').addEventListener('click', () => downloadPng(el.preview.textContent)); el.testAll.addEventListener('click', showAllFonts);
fetch('/api/fonts').then((response) => response.json()).then((data) => { fonts = data.fonts; fillFonts(); render(); }).catch((error) => { el.notice.textContent = `Font load failed: ${error.message}`; });
